Path = "/home/qmiao/Desktop/n3/n3-sif2json/Server/config.toml"
Service = "n3-sif2json"

[Route]
HELP = "/"
JSON2SIF = "/n3-sif2json/v0.2.8/json2sif"
SIF2JSON = "/n3-sif2json/v0.2.8/sif2json"

[Server]
IP = "192.168.31.168"
Port = 1324
Protocol = "http"

[Access]
Timeout = 3
