Path = "/home/qmiao/Desktop/n3/n3-sif2json/Server/go-client/config.toml"
Service = "n3-sif2json"
Version = "v0.2.2"

[Server]
  Protocol = "http"
  IP = "192.168.31.168"
  Port = 1324

[Access]
  Timeout = 3

[Route]
  HELP = "/"
  SIF2JSON = "/[s]/[v]/sif2json"
  JSON2SIF = "/[s]/[v]/json2sif"
