Path = "/home/qmiao/Desktop/n3/n3-sif2json/Server/go-client/config.toml"
LogFile = "./go-clt-SIF2JSON-[DATE].log"
ServiceName = "N3-SIF2JSON"

[Server]
  Protocol = "http"
  IP = "192.168.31.168"
  Port = 1324

[Access]
  Timeout = 3

[Route]
  HELP = "/"
  SIF2JSON = "/sif2json/v0.1.1"
  JSON2SIF = "/json2sif/v0.1.1"
