Path = "./config/cfg2json.toml"
PathAbs = "/home/qing/go/src/github.com/nsip/n3-sif2json/2JSON/config/cfg2json.toml"
JQDir = "/home/qing/go/src/github.com/cdutwhu/json-util/preprocess/utils"
Sep = "~"
CfgJSONOutDir = "../data/ListAttributes/"

[PurchaseOrder]
  ListAttrs = ["PurchasingItems", "PurchasingItems~PurchasingItem~ExpenseAccounts"]

[Test]
  ListAttrs = ["PurchasingItems", "PurchasingItems~PurchasingItem~ExpenseAccounts", "EmployeePersonalRefId"]
