Path = "./config/sif2json.toml"
PathAbs = "/home/qing/go/src/github.com/nsip/n3-sif2json/2JSON/config/sif2json.toml"
JQDir = "/home/qing/go/src/github.com/cdutwhu/json-util/preprocess/utils"
AttrPrefix = "-"
ContentPrefix = "#"
CfgJSONDir = "../data/ListAttributes/"
