Path = "/home/qing/go/src/github.com/nsip/n3-sif2json/2JSON/config/SIF2JSON.toml"
ELog = "./error.log"
JQDir = "/home/qing/go/src/github.com/cdutwhu/json-util/preprocess/utils"
AttrPrefix = "-"
ContentPrefix = "#"
DefaultSIFVer = "0.0.1"
SIFCfgDir4LIST = "../2JSON/SIFSpec/#SIFVER#/LIST/"
SIFCfgDir4NUM = "../2JSON/SIFSpec/#SIFVER#/NUMERIC/"
SIFCfgDir4BOOL = "../2JSON/SIFSpec/#SIFVER#/BOOLEAN/"
