Path = "./config/XML2JSON.toml"
PathAbs = "/home/qing/go/src/github.com/nsip/n3-sif2json/2JSON/config/XML2JSON.toml"
JQDir = "/home/qing/go/src/github.com/cdutwhu/json-util/preprocess/utils"
AttrPrefix = "-"
ContentPrefix = "#"
