Service = "n3-sif2json"

[Route]
  ToJSON = "/n3-sif2json/v0.4.6/2json"
  ToSIF = "/n3-sif2json/v0.4.6/2sif"
  Help = "/"

[Server]
  Port = 1324
  Protocol = "http"
  IP = "192.168.31.168"

[Access]
  Timeout = 10
