Service = "n3-sif2json"

[Route]
  Help = "/"
  ToJSON = "/n3-sif2json/v0.4.10/2json"
  ToSIF = "/n3-sif2json/v0.4.10/2sif"

[Server]
  IP = "192.168.31.168"
  Port = 1324
  Protocol = "http"

[Access]
  Timeout = 10
