Service = "n3-sif2json"

[Route]
  ToJSON = "/n3-sif2json/v0.4.9/2json"
  ToSIF = "/n3-sif2json/v0.4.9/2sif"
  Help = "/"

[Server]
  Protocol = "http"
  IP = "192.168.31.168"
  Port = 1324

[Access]
  Timeout = 10
