Service = "n3-sif2json"

[Route]
  ToSIF = "/n3-sif2json/v0.4.10/2sif"
  Help = "/"
  ToJSON = "/n3-sif2json/v0.4.10/2json"

[Server]
  Port = 1324
  Protocol = "http"
  IP = "192.168.31.168"

[Access]
  Timeout = 10
