Path = "/home/qing/go/src/github.com/nsip/n3-sif2json/Client/config/config.toml"
ELog = "/home/qing/go/src/github.com/nsip/n3-sif2json/Client/error.log"

[Server]
  Protocol = "http"
  IP = "192.168.92.154"
  Port = 1324

[Access]
  Timeout = 3

[Route]
  API = "/"
  SIF2JSON = "/sif2json/0.1.0"
  JSON2SIF = "/json2sif/0.1.0"
