Path = "/home/qing/go/src/github.com/nsip/n3-sif2json/Client/config/config.toml"
LogFile = "/home/qmiao/go/src/github.com/nsip/n3-sif2json/Client/error.log"

[Server]
  Protocol = "http"
  IP = "127.0.0.1"
  Port = 1324

[Access]
  Timeout = 3

[Route]
  HELP = "/"
  SIF2JSON = "/sif2json/0.1.0"
  JSON2SIF = "/json2sif/0.1.0"
