Path = "/home/qmiao/Desktop/n3/n3-sif2json/Server/config/config.toml"
Log = "~/.[s]/log/[DATE].log"
Cfg2JSON = "../../../2JSON/config/config.toml"
Cfg2SIF = "../../../2SIF/config/config.toml"
Service = "n3-sif2json"
Version = "v0.2.2"

[WebService]
  Port = 1324

[Route]
  HELP = "/"
  SIF2JSON = "/[s]/[v]/sif2json"
  JSON2SIF = "/[s]/[v]/json2sif"

[NATS]
  URL = "nats://192.168.78.130:4222"
  Subject = "SIF2JSON"
  Timeout = 500

[File]
  ClientLinux64 = "../../../Client/build/linux64/client"
  ClientMac = "../../../Client/build/mac/client"
  ClientWin64 = "../../../Client/build/win64/client.exe"
  ClientConfig = "../../../Client/build/linux64/cfg-clt-sif2json.toml"
