Path = "/home/qing/go/src/github.com/nsip/n3-sif2json/Server/config/config.toml"
ELog = "/home/qing/go/src/github.com/nsip/n3-sif2json/Server/error.log"

[WebService]
  Port = 1324
  Version = "0.1.0"

[Route]
  ROOT = "/"
  SIF2JSON = "/sif2json/#v"
  JSON2SIF = "/json2sif/#v"
