Path = "config/config.toml"
ELog = "error.log"
Cfg2JSON = "../2JSON/config/SIF2JSON.toml"
Cfg2SIF = "../2SIF/config/JSON2SIF.toml"

[WebService]
  Port = 8091
  Version = "0.1.0"

[Route]
  ROOT = "/"
  SIF2JSON = "/sif2json/#v"
  JSON2SIF = "/json2sif/#v"

[NATS]
  URL = "nats://192.168.78.130:4222"
  Subject = "SIF2JSON"
  Timeout = 500
