Path = "/home/qmiao/Desktop/n3/n3-sif2json/2SIF/config/config.toml"
LogFile = "./[DATE].log"
DefaultSIFVer = "3.4.7"
SIFSpecDir = "../../../SIFSpec/"
ReplCfgPath = "../../../2SIF/config/replace.json"
