Path = "/home/qmiao/go/src/github.com/nsip/n3-sif2json/2SIF/config/Config.toml"
LogFile = "./error.log"
DefaultSIFVer = "3.4.6"
SIFSpecDir = "../../../SIFSpec/"
ReplCfgPath = "../../../2SIF/config/replace.json"
