Path = "/home/qing/go/src/github.com/nsip/n3-sif2json/2SIF/config/JSON2SIF.toml"
LogFile = "./error.log"
DefaultSIFVer = "0.0.1"
SIFSpecDir = "../SIFSpec/"
ReplCfgPath = "../2SIF/config/replace.json"
