Path = "/home/qmiao/Desktop/n3-sif2json/Server/config.toml"
Service = "n3-sif2json"

[Route]
  SIF2JSON = "/n3-sif2json/v0.3.6/sif2json"
  JSON2SIF = "/n3-sif2json/v0.3.6/json2sif"
  HELP = "/"

[Server]
  IP = "192.168.31.168"
  Port = 1324
  Protocol = "http"

[Access]
  Timeout = 3
