Path = "/home/qmiao/Desktop/n3-sif2json/Server/config.toml"
Service = "n3-sif2json"

[Route]
  JSON2SIF = "/n3-sif2json/v0.3.6/json2sif"
  HELP = "/"
  SIF2JSON = "/n3-sif2json/v0.3.6/sif2json"

[Server]
  Port = 1324
  Protocol = "http"
  IP = "192.168.31.168"

[Access]
  Timeout = 3
