Service = "n3-sif2json"
Path = "/home/qmiao/Desktop/n3-sif2json/Server/config.toml"

[Route]
  HELP = "/"
  SIF2JSON = "/n3-sif2json//sif2json"
  JSON2SIF = "/n3-sif2json//json2sif"

[Server]
  Port = 1324
  Protocol = "http"
  IP = "192.168.31.168"

[Access]
  Timeout = 3
