Path = "[PATH]"
Service = "[PRJ]"
Log = "~/.[PRJ]/log/[DATE].log"
Version = "[VER]"

[Loggly]
  Token = "54290728-93e0-425a-a49c-c9e834288026"

[WebService]
  Port = 1324

[Route]
  HELP = "/"
  SIF2JSON = "/[PRJ]/[VER]/sif2json"
  JSON2SIF = "/[PRJ]/[VER]/json2sif"

[NATS]
  Timeout = 500
  URL = "nats://192.168.78.130:4222"
  Subject = "SIF2JSON"

[Server]
  Port = "[port]"
  Protocol = "http"
  IP = "[IP]"

[Access]
  Timeout = 3
