Path = "[PATH]"
Service = "n3-sif2json"
Log = "~/.[s]/log/[DATE].log"
Cfg2JSON = "../../../2JSON/config.toml"
Cfg2SIF = "../../../2SIF/config.toml"
Version = "v0.2.8"

[Loggly]
  Token = "54290728-93e0-425a-a49c-c9e834288026"

[WebService]
  Port = 1324

[Route]
  HELP = "/"
  SIF2JSON = "/[s]/[v]/sif2json"
  JSON2SIF = "/[s]/[v]/json2sif"

[NATS]
  Timeout = 500
  URL = "nats://192.168.78.130:4222"
  Subject = "SIF2JSON"

[Server]
  Port = "[port]"
  Protocol = "http"
  IP = "[IP]"

[Access]
  Timeout = 3
